# Generated by Django 5.1 on 2024-08-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='manual_location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('early bird', 'early bird'), ('giveaway', 'giveaway'), ('regular', 'regular')], max_length=50),
        ),
    ]
