# Generated by Django 5.1 on 2024-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upcoming_events',
            field=models.BooleanField(default=False),
        ),
    ]
