# Generated by Django 5.1 on 2024-08-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_upcoming_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Concert', 'Concert'), ('Webinar', 'Webinar')], default='Conference', max_length=50),
        ),
    ]
