# Generated by Django 5.1 on 2024-08-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Concert', 'Concert'), ('Webinar', 'Webinar')], default='', max_length=50),
        ),
    ]
