# Generated by Django 5.1 on 2024-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_payment_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Concert', 'Concert'), ('Webinar', 'Webinar'), ('Networking', 'Networking'), ('Social', 'Social'), ('Corporate', 'Corporate'), ('Charity & Fundraising', 'Charity & Fundraising'), ('Cultural', 'Cultural'), ('Entertainment', 'Entertainment'), ('Sporting', 'Sporting'), ('Political', 'Political'), ('Fashion', 'Fashion')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('VVIP', 'VVIP'), ('early bird', 'early bird'), ('giveaway', 'giveaway'), ('regular', 'regular')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
