# Generated by Django 5.1 on 2024-08-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_giveaway_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='giveaway_events',
            new_name='giveaway',
        ),
    ]
