# Generated by Django 5.1 on 2024-09-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
