# Generated by Django 5.1 on 2024-09-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_advance_ticket_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='advance_ticket_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gate_adult_ticket_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gate_kid_ticket_price',
        ),
    ]
