# Generated by Django 5.1 on 2024-09-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_event_location_type_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
