# Generated by Django 5.1 on 2024-09-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_ticket_ticket_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_pdf',
        ),
    ]
