# Generated by Django 5.1 on 2024-09-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_remove_ticket_ticket_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
