# Generated by Django 5.1 on 2024-09-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_ticket_ticket_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='early_bird_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='vvip_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
