# Generated by Django 5.1 on 2024-09-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_early_bird_price_event_regular_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
